### ISSUE TITLE
Does not show how many records were parsed

### ISSUE THREAD

**Issue by crow1170** [AnEmortalKid/reddit-parser#2]
This code is being used to track the 10,000 Subscribers celebration at http://www.reddit.com/r/DnDBehindTheScreen/. In light of this, a big banner at the top of the output saying how many records were parsed would show how close any given are is to completion. Example: 10,000 Mysteries (currently 844).

**Comment by AnEmortalKid** [comment]
Ideally, the SiteBuilder (or whatever class we want to use to generate the index page for each list) will place the banner at the top. I'm adding them manually at the moment.

**Comment by AnEmortalKid** [comment]
https://github.com/AnEmortalKid/reddit-parser/commit/8f8c996b85c4df61ccac5c0ebd899b0e5068cb33

Code has been updated to generate a site with an h2 showing Currently at X /10000
